In [29]:
import pandas as pd
import numpy as np
import dateutil.parser
import datetime
import csv

In [30]:
chars_data = pd.read_csv("Chars_population_data.csv")
world_data = pd.read_csv("WDIData.csv")
coutries_data = pd.read_csv("allCountriesCodes.csv")

In [31]:
coutries_data.head()

,name,ISO,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Aland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN

In [32]:
coutries_data = coutries_data.drop(['ISO', 'country-code', 'iso_3166-2', 'intermediate-region', 'region-code', 'sub-region-code', 
               'intermediate-region-code'], axis=1)
coutries_data.columns = ['Country Name','Country Code','Region','Sub-region']
coutries_data

,Country Name,Country Code,Region,Sub-region
0,Afghanistan,AFG,Asia,Southern Asia
1,Aland Islands,ALA,Europe,Northern Europe
2,Albania,ALB,Europe,Southern Europe
3,Algeria,DZA,Africa,Northern Africa
4,American Samoa,ASM,Oceania,Polynesia
5,Andorra,AND,Europe,Southern Europe
6,Angola,AGO,Africa,Sub-Saharan Africa
7,Anguilla,AIA,Americas,Latin America and the Caribbean
8,Antarctica,ATA,NaN,NaN
9,Antigua and Barbuda,ATG,Americas,Latin America and the Caribbean
10,Argentina,ARG,Americas,Latin America and the Caribbean
11,Armenia,ARM,Asia,Western Asia
12,Aruba,ABW,Americas,Latin America and the Caribbean
13,Australia,AUS,Oceania,Australia and New Zealand
14,Austria,AUT,Europe,Western Europe
15,Azerbaijan,AZE,Asia,Western Asia
16,Bahamas,BHS,Americas,Latin America and the Caribbean
17,Bahrain,BHR,Asia,Western Asia
18,Bangladesh,BGD,Asia,Southern Asia
19,Barbados,BRB,Americas,Latin America and the Caribbean
20,Belarus,BLR,Europe,Eastern Europe
21,Belgium,BEL,Europe,Western Europe
22,Belize,BLZ,Americas,Latin America and the Caribbean
23,Benin,BEN,Africa,Sub-Saharan Africa
24,Bermuda,BMU,Americas,Northern America
25,Bhutan,BTN,Asia,Southern Asia
26,Bolivia (Plurinational State of),BOL,Americas,Latin America and the Caribbean
27,"Bonaire, Sint Eustatius and Saba",BES,Americas,Latin America and the Caribbean
28,Bosnia and Herzegovina,BIH,Europe,Southern Europe
29,Botswana,BWA,Africa,Sub-Saharan Africa
...,...,...,...,...
219,"Tanzania, United Republic of",TZA,Africa,Sub-Saharan Africa
220,Thailand,THA,Asia,South-eastern Asia
221,Timor-Leste,TLS,Asia,South-eastern Asia
222,Togo,TGO,Africa,Sub-Saharan Africa
223,Tokelau,TKL,Oceania,Polynesia
224,Tonga,TON,Oceania,Polynesia
225,Trinidad and Tobago,TTO,Americas,Latin America and the Caribbean
226,Tunisia,TUN,Africa,Northern Africa
227,Turkey,TUR,Asia,Western Asia
228,Turkmenistan,TKM,Asia,Central Asia
229,Turks and Caicos Islands,TCA,Americas,Latin America and the Caribbean
230,Tuvalu,TUV,Oceania,Polynesia
231,Uganda,UGA,Africa,Sub-Saharan Africa
232,Ukraine,UKR,Europe,Eastern Europe
233,United Arab Emirates,ARE,Asia,Western Asia
234,United Kingdom of Great Britain and Northern I...,GBR,Europe,Northern Europe
235,United States of America,USA,Americas,Northern America
236,United States Minor Outlying Islands,UMI,Oceania,Micronesia
237,Uruguay,URY,Americas,Latin America and the Caribbean
238,Uzbekistan,UZB,Asia,Central Asia
239,Vanuatu,VUT,Oceania,Melanesia
240,Venezuela (Bolivarian Republic of),VEN,Americas,Latin America and the Caribbean
241,Viet Nam,VNM,Asia,South-eastern Asia
242,Virgin Islands (British),VGB,Americas,Latin America and the Caribbean
243,Virgin Islands (U.S.),VIR,Americas,Latin America and the Caribbean
244,Wallis and Futuna,WLF,Oceania,Polynesia
245,Western Sahara,ESH,Africa,Northern Africa
246,Yemen,YEM,Asia,Western Asia
247,Zambia,ZMB,Africa,Sub-Saharan Africa
248,Zimbabwe,ZWE,Africa,Sub-Saharan Africa

In [ ]:
world_data = world_data.drop(['Indicator Code', '1960', '1961',
       '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970',
       '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979',
       '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988',
       '1989','Unnamed: 63'], axis=1)
world_data.columns

Index(['Country Name', 'Country Code', 'Indicator Name', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018'],
      dtype='object')

In [ ]:
countries_all = pd.merge(world_data, coutries_data, on='Country Code', how='left')
countries_all

In [ ]:
#countries_all.isnull().any()
nan_rows = countries_all[countries_all['Country Name_y'].isnull()]
countries_list=nan_rows['Country Name_x']
countries_list
myset = set(countries_list)
myset.remove('World')
#type(myset)
myset

In [ ]:
countries_all = countries_all[~countries_all['Country Name_x'].isin(myset)]
countries_all

In [ ]:
indicators_list = {#Access
    'Access to clean fuels and technologies for cooking (% of population)',
    'Access to electricity (% of population)',
    'Access to electricity, rural (% of rural population)',
    'Access to electricity, urban (% of urban population)',
    'Individuals using the Internet (% of population)',
    'Educational attainment, at least Bachelor\'s or equivalent, population 25+, total (%) (cumulative)',
    'Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)',
    'Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)',
    'Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)',
    'Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)',
    'Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)',
    'Educational attainment, at least Master\'s or equivalent, population 25+, total (%) (cumulative)',
    'Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)',
    'Electric power consumption (kWh per capita)',
    'Electricity production from coal sources (% of total)',
    'Electricity production from hydroelectric sources (% of total)',
    'Electricity production from natural gas sources (% of total)',
    'Electricity production from nuclear sources (% of total)',
    'Electricity production from oil sources (% of total)',
    'Electricity production from renewable sources, excluding hydroelectric (% of total)',
    'People using at least basic drinking water services (% of population)',
    'People using at least basic drinking water services, rural (% of rural population)',
    'People using at least basic drinking water services, urban (% of urban population)',
    'People using safely managed drinking water services (% of population)',
    'People using safely managed drinking water services, rural (% of rural population)',
    'People using safely managed drinking water services, urban (% of urban population)',
    'People using at least basic sanitation services (% of population)',
    'People using at least basic sanitation services, rural (% of rural population)',
    'People using at least basic sanitation services, urban (% of urban population)',
    'Population ages 0-14 (% of total)',
    'Population ages 15-64 (% of total)',
    'Population ages 65 and above (% of total)',
    'Population, total',
    'Income share held by lowest 10%',
    'Adjusted net national income (current US$)',
    'Population ages 0-14, female (% of total)',
    'Population ages 0-14, male (% of total)',
    'Population ages 10-14, female (% of female population)',
    'Population ages 10-14, male (% of male population)',
    'Population ages 5-9, female (% of female population)',
    'Population ages 5-9, male (% of male population)'
    }
len(indicators_list)

In [10]:
countries_all = countries_all[countries_all['Indicator Name'].isin(indicators_list)]
countries_all

,Country Name_x,Country Code,Indicator Name,1990,1991,1992,1993,1994,1995,1996,...,2012,2013,2014,2015,2016,2017,2018,Country Name_y,Region,Sub-region
73556,World,WLD,Access to clean fuels and technologies for coo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.726934e+01,5.786835e+01,5.836695e+01,5.884796e+01,5.935046e+01,NaN,NaN,NaN,NaN,NaN
73557,World,WLD,Access to electricity (% of population),7.139056e+01,7.159899e+01,7.258230e+01,7.323515e+01,7.352205e+01,7.402376e+01,7.515322e+01,...,8.506858e+01,8.518812e+01,8.571745e+01,8.705535e+01,8.737785e+01,NaN,NaN,NaN,NaN,NaN
73558,World,WLD,"Access to electricity, rural (% of rural popul...",6.284804e+01,6.129154e+01,6.367869e+01,6.272376e+01,6.244634e+01,6.243758e+01,6.330544e+01,...,7.361726e+01,7.421249e+01,7.431056e+01,7.791087e+01,7.748678e+01,NaN,NaN,NaN,NaN,NaN
73559,World,WLD,"Access to electricity, urban (% of urban popul...",9.282149e+01,9.277559e+01,9.301585e+01,9.297680e+01,9.339986e+01,9.357121e+01,9.373763e+01,...,9.614535e+01,9.624873e+01,9.634531e+01,9.652479e+01,9.690096e+01,NaN,NaN,NaN,NaN,NaN
73578,World,WLD,Adjusted net national income (current US$),1.855646e+13,1.970040e+13,2.097966e+13,2.126760e+13,2.291141e+13,2.551662e+13,2.617367e+13,...,6.145483e+13,6.305034e+13,6.510757e+13,6.189798e+13,6.268628e+13,6.629313e+13,NaN,NaN,NaN,NaN
73923,World,WLD,"Educational attainment, at least Bachelor's or...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73926,World,WLD,"Educational attainment, at least completed low...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73929,World,WLD,"Educational attainment, at least completed pos...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73932,World,WLD,"Educational attainment, at least completed pri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73935,World,WLD,"Educational attainment, at least completed sho...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73938,World,WLD,"Educational attainment, at least completed upp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73941,World,WLD,"Educational attainment, at least Master's or e...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73944,World,WLD,"Educational attainment, Doctoral or equivalent...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73945,World,WLD,Electric power consumption (kWh per capita),2.124756e+03,2.150596e+03,2.131280e+03,2.137364e+03,2.160488e+03,2.197898e+03,2.236965e+03,...,3.046442e+03,3.106072e+03,3.127480e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73947,World,WLD,Electricity production from coal sources (% of...,3.700596e+01,3.707383e+01,3.740906e+01,3.737778e+01,3.752753e+01,3.735181e+01,3.796492e+01,...,4.027716e+01,4.104493e+01,4.048805e+01,3.916759e+01,NaN,NaN,NaN,NaN,NaN,NaN
73948,World,WLD,Electricity production from hydroelectric sour...,1.792874e+01,1.808561e+01,1.791454e+01,1.852809e+01,1.824376e+01,1.853622e+01,1.820654e+01,...,1.606184e+01,1.614790e+01,1.624387e+01,1.589844e+01,NaN,NaN,NaN,NaN,NaN,NaN
73949,World,WLD,Electricity production from natural gas source...,1.473076e+01,1.462477e+01,1.460747e+01,1.471169e+01,1.491854e+01,1.517775e+01,1.519256e+01,...,2.239041e+01,2.149070e+01,2.159761e+01,2.278882e+01,NaN,NaN,NaN,NaN,NaN,NaN
73950,World,WLD,Electricity production from nuclear sources (%...,1.692028e+01,1.730790e+01,1.730394e+01,1.743042e+01,1.741537e+01,1.751159e+01,1.759344e+01,...,1.081755e+01,1.058607e+01,1.060738e+01,8.117982e+00,NaN,NaN,NaN,NaN,NaN,NaN
73951,World,WLD,Electricity production from oil sources (% of ...,1.020776e+01,1.004163e+01,9.723763e+00,9.108013e+00,8.842378e+00,8.489620e+00,8.095212e+00,...,4.155986e+00,3.783813e+00,3.547839e+00,3.279626e+00,NaN,NaN,NaN,NaN,NaN,NaN
73953,World,WLD,"Electricity production from renewable sources,...",1.312012e+00,1.030697e+00,1.130682e+00,1.145608e+00,1.177292e+00,1.183011e+00,1.179409e+00,...,4.695464e+00,5.410807e+00,6.006731e+00,6.765609e+00,NaN,NaN,NaN,NaN,NaN,NaN
74212,World,WLD,Income share held by lowest 10%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74220,World,WLD,Individuals using the Internet (% of population),4.934308e-02,NaN,NaN,2.518469e-01,4.470307e-01,7.774425e-01,1.325952e+00,...,3.419343e+01,3.672464e+01,3.977195e+01,4.296296e+01,4.567329e+01,4.856513e+01,NaN,NaN,NaN,NaN
74584,World,WLD,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.719418e+01,8.761620e+01,8.804518e+01,8.846340e+01,NaN,NaN,NaN,NaN,NaN,NaN
74585,World,WLD,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.799711e+01,7.873851e+01,7.950676e+01,8.026930e+01,NaN,NaN,NaN,NaN,NaN,NaN
74586,World,WLD,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.515573e+01,9.515250e+01,9.515484e+01,9.515407e+01,NaN,NaN,NaN,NaN,NaN,NaN
74587,World,WLD,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.613124e+01,6.676844e+01,6.739631e+01,6.800766e+01,NaN,NaN,NaN,NaN,NaN,NaN
74588,World,WLD,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.748622e+01,4.827524e+01,4.905715e+01,4.982652e+01,NaN,NaN,NaN,NaN,NaN,NaN
74589,World,WLD,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.123359e+01,8.147656e+01,8.172023e+01,8.195379e+01,NaN,NaN,NaN,NaN,NaN,NaN
74590,World,WLD,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.122000e+01,7.109000e+01,7.114000e+01,7.116000e+01,NaN,NaN,NaN,NaN,NaN,NaN
74591,World,WLD,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.577000e+01,5.522000e+01,5.503000e+01,5.481000e+01,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420924,Zimbabwe,ZWE,"Educational attainment, at least Master's or e...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
420927,Zimbabwe,ZWE,"Educational attainment, Doctoral or equivalent...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
420928,Zimbabwe,ZWE,Electric power consumption (kWh per capita),8.865658e+02,8.756069e+02,8.032487e+02,7.498792e+02,7.877162e+02,8.295683e+02,8.690547e+02,...,5.427296e+02,5.575739e+02,5.369955e+02,NaN,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
420930,Zimbabwe,ZWE,Electricity production from coal sources (% of...,5.333262e+01,6.467952e+01,6.162438e+01,7.238886e+01,7.219642e+01,7.074638e+01,7.046293e+01,...,3.905248e+01,4.546499e+01,4.385597e+01,4.678134e+01,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
420931,Zimbabwe,ZWE,Electricity production from hydroelectric sour...,4.666738e+01,3.532048e+01,3.837562e+01,2.761114e+01,2.780358e+01,2.925362e+01,2.953707e+01,...,5.856786e+01,5.220481e+01,5.416916e+01,5.139561e+01,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
420932,Zimbabwe,ZWE,Electricity production from natural gas source...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
420933,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
420934,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,5.541671e-01,5.956113e-01,5.385996e-01,4.943867e-01,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
420936,Zimbabwe,ZWE,"Electricity production from renewable sources,...",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.825492e+00,1.734587e+00,1.436266e+00,1.328664e+00,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421195,Zimbabwe,ZWE,Income share held by lowest 10%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421203,Zimbabwe,ZWE,Individuals using the Internet (% of population),0.000000e+00,NaN,NaN,NaN,1.739280e-03,7.683540e-03,1.679048e-02,...,1.200000e+01,1.550000e+01,1.636474e+01,2.274282e+01,2.311999e+01,2.705549e+01,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421567,Zimbabwe,ZWE,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.745491e+01,6.714763e+01,6.685015e+01,6.656310e+01,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421568,Zimbabwe,ZWE,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.451271e+01,5.418671e+01,5.386070e+01,5.353470e+01,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421569,Zimbabwe,ZWE,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.392976e+01,9.387838e+01,9.382701e+01,9.377563e+01,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421570,Zimbabwe,ZWE,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.930836e+01,3.906346e+01,3.882338e+01,3.858862e+01,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421571,Zimbabwe,ZWE,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.219189e+01,3.187532e+01,3.155875e+01,3.124219e+01,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421572,Zimbabwe,ZWE,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.386597e+01,5.388837e+01,5.391077e+01,5.393317e+01,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421573,Zimbabwe,ZWE,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421574,Zimbabwe,ZWE,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421575,Zimbabwe,ZWE,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421616,Zimbabwe,ZWE,Population ages 0-14 (% of total),4.633496e+01,4.612020e+01,4.586621e+01,4.555437e+01,4.516624e+01,4.470056e+01,4.440694e+01,...,4.150027e+01,4.150749e+01,4.150439e+01,4.147056e+01,4.137941e+01,4.120489e+01,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421618,Zimbabwe,ZWE,"Population ages 0-14, female (% of total)",4.589808e+01,4.562695e+01,4.531418e+01,4.494361e+01,4.450081e+01,4.398665e+01,4.364961e+01,...,4.029320e+01,4.029439e+01,4.028554e+01,4.024699e+01,4.018078e+01,4.003326e+01,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421620,Zimbabwe,ZWE,"Population ages 0-14, male (% of total)",4.677831e+01,4.662200e+01,4.642900e+01,4.617831e+01,4.584752e+01,4.543282e+01,4.518505e+01,...,4.277258e+01,4.278640e+01,4.278976e+01,4.276124e+01,4.264222e+01,4.243784e+01,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421624,Zimbabwe,ZWE,"Population ages 10-14, female (% of female pop...",1.342925e+01,1.355841e+01,1.367430e+01,1.377110e+01,1.383218e+01,1.383553e+01,1.381937e+01,...,1.165486e+01,1.155369e+01,1.149584e+01,1.148961e+01,1.150001e+01,1.156224e+01,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421625,Zimbabwe,ZWE,"Population ages 10-14, male (% of male populat...",1.363067e+01,1.378501e+01,1.393542e+01,1.407271e+01,1.417552e+01,1.421793e+01,1.423044e+01,...,1.232652e+01,1.222080e+01,1.216409e+01,1.216496e+01,1.216317e+01,1.221913e+01,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421628,Zimbabwe,ZWE,Population ages 15-64 (% of total),5.067619e+01,5.086693e+01,5.109750e+01,5.138777e+01,5.175832e+01,5.221158e+01,5.248333e+01,...,5.554467e+01,5.559366e+01,5.564288e+01,5.570585e+01,5.580503e+01,5.597321e+01,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421650,Zimbabwe,ZWE,"Population ages 5-9, female (% of female popul...",1.561565e+01,1.555846e+01,1.542504e+01,1.521990e+01,1.496972e+01,1.471142e+01,1.455195e+01,...,1.308626e+01,1.317706e+01,1.328300e+01,1.337006e+01,1.343616e+01,1.351151e+01,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421651,Zimbabwe,ZWE,"Population ages 5-9, male (% of male population)",1.589820e+01,1.588925e+01,1.579862e+01,1.562984e+01,1.541155e+01,1.518333e+01,1.505500e+01,...,1.387705e+01,1.398058e+01,1.409976e+01,1.419628e+01,1.425042e+01,1.431693e+01,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421654,Zimbabwe,ZWE,Population ages 65 and above (% of total),2.988850e+00,3.012877e+00,3.036282e+00,3.057862e+00,3.075439e+00,3.087856e+00,3.109723e+00,...,2.955062e+00,2.898853e+00,2.852733e+00,2.823593e+00,2.815553e+00,2.821904e+00,NaN,Zimbabwe,Africa,Sub-Saharan Africa
421680,Zimbabwe,ZWE,"Population, total",1.018311e+07,1.044304e+07,1.068287e+07,1.090576e+07,1.111695e+07,1.132035e+07,1.151826e+07,...,1.471083e+07,1.505451e+07,1.541168e+07,1.577745e+07,1.615036e+07,1.652990e+07,NaN,Zimbabwe,Africa,Sub-Saharan Africa

In [11]:
countries_all = countries_all[['Country Name_x','Country Name_y', 'Region', 'Sub-region', 'Country Code', 'Indicator Name', 
                               '1990', '1991','1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
                               '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009','2010', '2011', 
                               '2012', '2013', '2014', '2015', '2016', '2017', '2018']]
countries_all = countries_all.drop(['Country Name_x'], axis=1)
countries_all.columns = ['Country Name', 'Region', 'Sub-region', 'Country Code', 'Indicator Name', 
                               '1990', '1991','1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
                               '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009','2010', '2011', 
                               '2012', '2013', '2014', '2015', '2016', '2017', '2018']
countries_all

,Country Name,Region,Sub-region,Country Code,Indicator Name,1990,1991,1992,1993,1994,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
73556,NaN,NaN,NaN,WLD,Access to clean fuels and technologies for coo...,NaN,NaN,NaN,NaN,NaN,...,5.533039e+01,5.606994e+01,5.663445e+01,5.726934e+01,5.786835e+01,5.836695e+01,5.884796e+01,5.935046e+01,NaN,NaN
73557,NaN,NaN,NaN,WLD,Access to electricity (% of population),7.139056e+01,7.159899e+01,7.258230e+01,7.323515e+01,7.352205e+01,...,8.320895e+01,8.353668e+01,8.250230e+01,8.506858e+01,8.518812e+01,8.571745e+01,8.705535e+01,8.737785e+01,NaN,NaN
73558,NaN,NaN,NaN,WLD,"Access to electricity, rural (% of rural popul...",6.284804e+01,6.129154e+01,6.367869e+01,6.272376e+01,6.244634e+01,...,7.111256e+01,7.141397e+01,6.909967e+01,7.361726e+01,7.421249e+01,7.431056e+01,7.791087e+01,7.748678e+01,NaN,NaN
73559,NaN,NaN,NaN,WLD,"Access to electricity, urban (% of urban popul...",9.282149e+01,9.277559e+01,9.301585e+01,9.297680e+01,9.339986e+01,...,9.584857e+01,9.565569e+01,9.589731e+01,9.614535e+01,9.624873e+01,9.634531e+01,9.652479e+01,9.690096e+01,NaN,NaN
73578,NaN,NaN,NaN,WLD,Adjusted net national income (current US$),1.855646e+13,1.970040e+13,2.097966e+13,2.126760e+13,2.291141e+13,...,4.932226e+13,5.403049e+13,5.969237e+13,6.145483e+13,6.305034e+13,6.510757e+13,6.189798e+13,6.268628e+13,6.629313e+13,NaN
73923,NaN,NaN,NaN,WLD,"Educational attainment, at least Bachelor's or...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73926,NaN,NaN,NaN,WLD,"Educational attainment, at least completed low...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73929,NaN,NaN,NaN,WLD,"Educational attainment, at least completed pos...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73932,NaN,NaN,NaN,WLD,"Educational attainment, at least completed pri...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73935,NaN,NaN,NaN,WLD,"Educational attainment, at least completed sho...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73938,NaN,NaN,NaN,WLD,"Educational attainment, at least completed upp...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73941,NaN,NaN,NaN,WLD,"Educational attainment, at least Master's or e...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73944,NaN,NaN,NaN,WLD,"Educational attainment, Doctoral or equivalent...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73945,NaN,NaN,NaN,WLD,Electric power consumption (kWh per capita),2.124756e+03,2.150596e+03,2.131280e+03,2.137364e+03,2.160488e+03,...,2.791239e+03,2.954882e+03,3.019707e+03,3.046442e+03,3.106072e+03,3.127480e+03,NaN,NaN,NaN,NaN
73947,NaN,NaN,NaN,WLD,Electricity production from coal sources (% of...,3.700596e+01,3.707383e+01,3.740906e+01,3.737778e+01,3.752753e+01,...,4.001760e+01,4.010962e+01,4.100100e+01,4.027716e+01,4.104493e+01,4.048805e+01,3.916759e+01,NaN,NaN,NaN
73948,NaN,NaN,NaN,WLD,Electricity production from hydroelectric sour...,1.792874e+01,1.808561e+01,1.791454e+01,1.852809e+01,1.824376e+01,...,1.607035e+01,1.588130e+01,1.570351e+01,1.606184e+01,1.614790e+01,1.624387e+01,1.589844e+01,NaN,NaN,NaN
73949,NaN,NaN,NaN,WLD,Electricity production from natural gas source...,1.473076e+01,1.462477e+01,1.460747e+01,1.471169e+01,1.491854e+01,...,2.191411e+01,2.239044e+01,2.197181e+01,2.239041e+01,2.149070e+01,2.159761e+01,2.278882e+01,NaN,NaN,NaN
73950,NaN,NaN,NaN,WLD,Electricity production from nuclear sources (%...,1.692028e+01,1.730790e+01,1.730394e+01,1.743042e+01,1.741537e+01,...,1.335159e+01,1.279410e+01,1.161067e+01,1.081755e+01,1.058607e+01,1.060738e+01,8.117982e+00,NaN,NaN,NaN
73951,NaN,NaN,NaN,WLD,Electricity production from oil sources (% of ...,1.020776e+01,1.004163e+01,9.723763e+00,9.108013e+00,8.842378e+00,...,4.183404e+00,3.812397e+00,4.021047e+00,4.155986e+00,3.783813e+00,3.547839e+00,3.279626e+00,NaN,NaN,NaN
73953,NaN,NaN,NaN,WLD,"Electricity production from renewable sources,...",1.312012e+00,1.030697e+00,1.130682e+00,1.145608e+00,1.177292e+00,...,3.128803e+00,3.552995e+00,4.098179e+00,4.695464e+00,5.410807e+00,6.006731e+00,6.765609e+00,NaN,NaN,NaN
74212,NaN,NaN,NaN,WLD,Income share held by lowest 10%,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74220,NaN,NaN,NaN,WLD,Individuals using the Internet (% of population),4.934308e-02,NaN,NaN,2.518469e-01,4.470307e-01,...,2.535634e+01,2.873360e+01,3.112451e+01,3.419343e+01,3.672464e+01,3.977195e+01,4.296296e+01,4.567329e+01,4.856513e+01,NaN
74584,NaN,NaN,NaN,WLD,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,8.584967e+01,8.634314e+01,8.674158e+01,8.719418e+01,8.761620e+01,8.804518e+01,8.846340e+01,NaN,NaN,NaN
74585,NaN,NaN,NaN,WLD,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,7.567894e+01,7.649635e+01,7.720623e+01,7.799711e+01,7.873851e+01,7.950676e+01,8.026930e+01,NaN,NaN,NaN
74586,NaN,NaN,NaN,WLD,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,9.519517e+01,9.519092e+01,9.515936e+01,9.515573e+01,9.515250e+01,9.515484e+01,9.515407e+01,NaN,NaN,NaN
74587,NaN,NaN,NaN,WLD,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,...,6.428904e+01,6.494004e+01,6.549097e+01,6.613124e+01,6.676844e+01,6.739631e+01,6.800766e+01,NaN,NaN,NaN
74588,NaN,NaN,NaN,WLD,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,...,4.526550e+01,4.603508e+01,4.670277e+01,4.748622e+01,4.827524e+01,4.905715e+01,4.982652e+01,NaN,NaN,NaN
74589,NaN,NaN,NaN,WLD,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,...,8.055983e+01,8.079758e+01,8.099366e+01,8.123359e+01,8.147656e+01,8.172023e+01,8.195379e+01,NaN,NaN,NaN
74590,NaN,NaN,NaN,WLD,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,6.990000e+01,7.082000e+01,7.114000e+01,7.122000e+01,7.109000e+01,7.114000e+01,7.116000e+01,NaN,NaN,NaN
74591,NaN,NaN,NaN,WLD,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,5.402000e+01,5.555000e+01,5.591000e+01,5.577000e+01,5.522000e+01,5.503000e+01,5.481000e+01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420924,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, at least Master's or e...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420927,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, Doctoral or equivalent...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420928,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electric power consumption (kWh per capita),8.865658e+02,8.756069e+02,8.032487e+02,7.498792e+02,7.877162e+02,...,5.310414e+02,5.468427e+02,5.702509e+02,5.427296e+02,5.575739e+02,5.369955e+02,NaN,NaN,NaN,NaN
420930,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from coal sources (% of...,5.333262e+01,6.467952e+01,6.162438e+01,7.238886e+01,7.219642e+01,...,2.407077e+01,3.171379e+01,4.165582e+01,3.905248e+01,4.546499e+01,4.385597e+01,4.678134e+01,NaN,NaN,NaN
420931,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from hydroelectric sour...,4.666738e+01,3.532048e+01,3.837562e+01,2.761114e+01,2.780358e+01,...,7.485942e+01,6.692441e+01,5.643446e+01,5.856786e+01,5.220481e+01,5.416916e+01,5.139561e+01,NaN,NaN,NaN
420932,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from natural gas source...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN
420933,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from nuclear sources (%...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN
420934,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from oil sources (% of ...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.880263e-01,2.769763e-01,4.882812e-01,5.541671e-01,5.956113e-01,5.385996e-01,4.943867e-01,NaN,NaN,NaN
420936,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Electricity production from renewable sources,...",0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,7.817858e-01,1.084824e+00,1.421441e+00,1.825492e+00,1.734587e+00,1.436266e+00,1.328664e+00,NaN,NaN,NaN
421195,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Income share held by lowest 10%,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.500000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421203,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Individuals using the Internet (% of population),0.000000e+00,NaN,NaN,NaN,1.739280e-03,...,4.000000e+00,6.400000e+00,8.400000e+00,1.200000e+01,1.550000e+01,1.636474e+01,2.274282e+01,2.311999e+01,2.705549e+01,NaN
421567,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,6.837236e+01,6.806728e+01,6.776159e+01,6.745491e+01,6.714763e+01,6.685015e+01,6.656310e+01,NaN,NaN,NaN
421568,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,5.549073e+01,5.516472e+01,5.483872e+01,5.451271e+01,5.418671e+01,5.386070e+01,5.353470e+01,NaN,NaN,NaN
421569,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,9.408389e+01,9.403251e+01,9.398114e+01,9.392976e+01,9.387838e+01,9.382701e+01,9.377563e+01,NaN,NaN,NaN
421570,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,...,4.003655e+01,3.979490e+01,3.955224e+01,3.930836e+01,3.906346e+01,3.882338e+01,3.858862e+01,NaN,NaN,NaN
421571,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,...,3.314159e+01,3.282502e+01,3.250845e+01,3.219189e+01,3.187532e+01,3.155875e+01,3.124219e+01,NaN,NaN,NaN
421572,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,NaN,NaN,NaN,NaN,NaN,...,5.379878e+01,5.382118e+01,5.384357e+01,5.386597e+01,5.388837e+01,5.391077e+01,5.393317e+01,NaN,NaN,NaN
421573,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421574,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421575,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421616,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 0-14 (% of total),4.633496e+01,4.612020e+01,4.586621e+01,4.555437e+01,4.516624e+01,...,4.149767e+01,4.152356e+01,4.150294e+01,4.150027e+01,4.150749e+01,4.150439e+01,4.147056e+01,4.137941e+01,4.120489e+01,NaN
421618,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, female (% of total)",4.589808e+01,4.562695e+01,4.531418e+01,4.494361e+01,4.450081e+01,...,4.031197e+01,4.032360e+01,4.030077e+01,4.029320e+01,4.029439e+01,4.028554e+01,4.024699e+01,4.018078e+01,4.003326e+01,NaN
421620,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, male (% of total)",4.677831e+01,4.662200e+01,4.642900e+01,4.617831e+01,4.584752e+01,...,4.274604e+01,4.278784e+01,4.276984e+01,4.277258e+01,4.278640e+01,4.278976e+01,4.276124e+01,4.264222e+01,4.243784e+01,NaN
421624,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, female (% of female pop...",1.342925e+01,1.355841e+01,1.367430e+01,1.377110e+01,1.383218e+01,...,1.209370e+01,1.196605e+01,1.179178e+01,1.165486e+01,1.155369e+01,1.149584e+01,1.148961e+01,1.150001e+01,1.156224e+01,NaN
421625,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, male (% of male populat...",1.363067e+01,1.378501e+01,1.393542e+01,1.407271e+01,1.417552e+01,...,1.279395e+01,1.266835e+01,1.247428e+01,1.232652e+01,1.222080e+01,1.216409e+01,1.216496e+01,1.216317e+01,1.221913e+01,NaN
421628,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 15-64 (% of total),5.067619e+01,5.086693e+01,5.109750e+01,5.138777e+01,5.175832e+01,...,5.541135e+01,5.542831e+01,5.548889e+01,5.554467e+01,5.559366e+01,5.564288e+01,5.570585e+01,5.580503e+01,5.597321e+01,NaN
421650,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, female (% of female popul...",1.561565e+01,1.555846e+01,1.542504e+01,1.521990e+01,1.496972e+01,...,1.304107e+01,1.303514e+01,1.303501e+01,1.308626e+01,1.317706e+01,1.328300e+01,1.337006e+01,1.343616e+01,1.351151e+01,NaN
421651,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, male (% of male population)",1.589820e+01,1.588925e+01,1.579862e+01,1.562984e+01,1.541155e+01,...,1.381527e+01,1.381538e+01,1.381711e+01,1.387705e+01,1.398058e+01,1.409976e+01,1.419628e+01,1.425042e+01,1.431693e+01,NaN
421654,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 65 and above (% of total),2.988850e+00,3.012877e+00,3.036282e+00,3.057862e+00,3.075439e+00,...,3.090981e+00,3.048128e+00,3.008164e+00,2.955062e+00,2.898853e+00,2.852733e+00,2.823593e+00,2.815553e+00,2.821904e+00,NaN
421680,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population, total",1.018311e+07,1.044304e+07,1.068287e+07,1.090576e+07,1.111695e+07,...,1.381060e+07,1.408632e+07,1.438665e+07,1.471083e+07,1.505451e+07,1.541168e+07,1.577745e+07,1.615036e+07,1.652990e+07,NaN

In [12]:
#last_v = countries_all[['1990', '1991','1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000','2001', '2002', 
#                        '2003', '2004', '2005', '2006', '2007', '2008', '2009','2010', '2011', '2012', '2013', '2014', '2015', 
#                        '2016', '2017', '2018']].max(axis=1)
#last_v
#countries_all['latest_value'] = last_v
#countries_all
print(*countries_all['Indicator Name'].unique(), sep = "\n")

Access to clean fuels and technologies for cooking (% of population)
Access to electricity (% of population)
Access to electricity, rural (% of rural population)
Access to electricity, urban (% of urban population)
Adjusted net national income (current US$)
Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)
Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)
Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)
Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)
Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)
Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)
Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)
Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)
Electric power consumption (kWh per capita)
Electricity production from coal sources (% of total)
Electricity production from hydroelectric sources (% of total)
Electricity production from natural gas sources (% of total)
Electricity production from nuclear sources (% of total)
Electricity production from oil sources (% of total)
Electricity production from renewable sources, excluding hydroelectric (% of total)
Income share held by lowest 10%
Individuals using the Internet (% of population)
People using at least basic drinking water services (% of population)
People using at least basic drinking water services, rural (% of rural population)
People using at least basic drinking water services, urban (% of urban population)
People using at least basic sanitation services (% of population)
People using at least basic sanitation services, rural (% of rural population)
People using at least basic sanitation services, urban (% of urban population)
People using safely managed drinking water services (% of population)
People using safely managed drinking water services, rural (% of rural population)
People using safely managed drinking water services, urban (% of urban population)
Population ages 0-14 (% of total)
Population ages 0-14, female (% of total)
Population ages 0-14, male (% of total)
Population ages 10-14, female (% of female population)
Population ages 10-14, male (% of male population)
Population ages 15-64 (% of total)
Population ages 5-9, female (% of female population)
Population ages 5-9, male (% of male population)
Population ages 65 and above (% of total)
Population, total

In [13]:
consolidated = countries_all.melt(id_vars=['Country Name', 'Region', 'Sub-region', 'Country Code', 'Indicator Name'], 
        var_name="Year", 
        value_name="Value")
consolidated

,Country Name,Region,Sub-region,Country Code,Indicator Name,Year,Value
0,NaN,NaN,NaN,WLD,Access to clean fuels and technologies for coo...,1990,NaN
1,NaN,NaN,NaN,WLD,Access to electricity (% of population),1990,7.139056e+01
2,NaN,NaN,NaN,WLD,"Access to electricity, rural (% of rural popul...",1990,6.284804e+01
3,NaN,NaN,NaN,WLD,"Access to electricity, urban (% of urban popul...",1990,9.282149e+01
4,NaN,NaN,NaN,WLD,Adjusted net national income (current US$),1990,1.855646e+13
5,NaN,NaN,NaN,WLD,"Educational attainment, at least Bachelor's or...",1990,NaN
6,NaN,NaN,NaN,WLD,"Educational attainment, at least completed low...",1990,NaN
7,NaN,NaN,NaN,WLD,"Educational attainment, at least completed pos...",1990,NaN
8,NaN,NaN,NaN,WLD,"Educational attainment, at least completed pri...",1990,NaN
9,NaN,NaN,NaN,WLD,"Educational attainment, at least completed sho...",1990,NaN
10,NaN,NaN,NaN,WLD,"Educational attainment, at least completed upp...",1990,NaN
11,NaN,NaN,NaN,WLD,"Educational attainment, at least Master's or e...",1990,NaN
12,NaN,NaN,NaN,WLD,"Educational attainment, Doctoral or equivalent...",1990,NaN
13,NaN,NaN,NaN,WLD,Electric power consumption (kWh per capita),1990,2.124756e+03
14,NaN,NaN,NaN,WLD,Electricity production from coal sources (% of...,1990,3.700596e+01
15,NaN,NaN,NaN,WLD,Electricity production from hydroelectric sour...,1990,1.792874e+01
16,NaN,NaN,NaN,WLD,Electricity production from natural gas source...,1990,1.473076e+01
17,NaN,NaN,NaN,WLD,Electricity production from nuclear sources (%...,1990,1.692028e+01
18,NaN,NaN,NaN,WLD,Electricity production from oil sources (% of ...,1990,1.020776e+01
19,NaN,NaN,NaN,WLD,"Electricity production from renewable sources,...",1990,1.312012e+00
20,NaN,NaN,NaN,WLD,Income share held by lowest 10%,1990,NaN
21,NaN,NaN,NaN,WLD,Individuals using the Internet (% of population),1990,4.934308e-02
22,NaN,NaN,NaN,WLD,People using at least basic drinking water ser...,1990,NaN
23,NaN,NaN,NaN,WLD,People using at least basic drinking water ser...,1990,NaN
24,NaN,NaN,NaN,WLD,People using at least basic drinking water ser...,1990,NaN
25,NaN,NaN,NaN,WLD,People using at least basic sanitation service...,1990,NaN
26,NaN,NaN,NaN,WLD,People using at least basic sanitation service...,1990,NaN
27,NaN,NaN,NaN,WLD,People using at least basic sanitation service...,1990,NaN
28,NaN,NaN,NaN,WLD,People using safely managed drinking water ser...,1990,NaN
29,NaN,NaN,NaN,WLD,People using safely managed drinking water ser...,1990,NaN
...,...,...,...,...,...,...,...
256794,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, at least Master's or e...",2018,NaN
256795,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, Doctoral or equivalent...",2018,NaN
256796,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electric power consumption (kWh per capita),2018,NaN
256797,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from coal sources (% of...,2018,NaN
256798,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from hydroelectric sour...,2018,NaN
256799,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from natural gas source...,2018,NaN
256800,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from nuclear sources (%...,2018,NaN
256801,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from oil sources (% of ...,2018,NaN
256802,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Electricity production from renewable sources,...",2018,NaN
256803,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Income share held by lowest 10%,2018,NaN
256804,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Individuals using the Internet (% of population),2018,NaN
256805,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,NaN
256806,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,NaN
256807,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,NaN
256808,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,NaN
256809,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,NaN
256810,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,NaN
256811,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,2018,NaN
256812,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,2018,NaN
256813,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,2018,NaN
256814,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 0-14 (% of total),2018,NaN
256815,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, female (% of total)",2018,NaN
256816,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, male (% of total)",2018,NaN
256817,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, female (% of female pop...",2018,NaN
256818,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, male (% of male populat...",2018,NaN
256819,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 15-64 (% of total),2018,NaN
256820,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, female (% of female popul...",2018,NaN
256821,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, male (% of male population)",2018,NaN
256822,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 65 and above (% of total),2018,NaN
256823,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population, total",2018,NaN

In [14]:
consolidated.loc[consolidated['Country Code'] == 'WLD', ['Country Name','Region','Sub-region']] = 'World'
consolidated['Group']=consolidated['Region']
consolidated.loc[consolidated['Country Name'] == 'Bangladesh', ['Group']] = 'Bangladesh'
consolidated

,Country Name,Region,Sub-region,Country Code,Indicator Name,Year,Value,Group
0,World,World,World,WLD,Access to clean fuels and technologies for coo...,1990,NaN,World
1,World,World,World,WLD,Access to electricity (% of population),1990,7.139056e+01,World
2,World,World,World,WLD,"Access to electricity, rural (% of rural popul...",1990,6.284804e+01,World
3,World,World,World,WLD,"Access to electricity, urban (% of urban popul...",1990,9.282149e+01,World
4,World,World,World,WLD,Adjusted net national income (current US$),1990,1.855646e+13,World
5,World,World,World,WLD,"Educational attainment, at least Bachelor's or...",1990,NaN,World
6,World,World,World,WLD,"Educational attainment, at least completed low...",1990,NaN,World
7,World,World,World,WLD,"Educational attainment, at least completed pos...",1990,NaN,World
8,World,World,World,WLD,"Educational attainment, at least completed pri...",1990,NaN,World
9,World,World,World,WLD,"Educational attainment, at least completed sho...",1990,NaN,World
10,World,World,World,WLD,"Educational attainment, at least completed upp...",1990,NaN,World
11,World,World,World,WLD,"Educational attainment, at least Master's or e...",1990,NaN,World
12,World,World,World,WLD,"Educational attainment, Doctoral or equivalent...",1990,NaN,World
13,World,World,World,WLD,Electric power consumption (kWh per capita),1990,2.124756e+03,World
14,World,World,World,WLD,Electricity production from coal sources (% of...,1990,3.700596e+01,World
15,World,World,World,WLD,Electricity production from hydroelectric sour...,1990,1.792874e+01,World
16,World,World,World,WLD,Electricity production from natural gas source...,1990,1.473076e+01,World
17,World,World,World,WLD,Electricity production from nuclear sources (%...,1990,1.692028e+01,World
18,World,World,World,WLD,Electricity production from oil sources (% of ...,1990,1.020776e+01,World
19,World,World,World,WLD,"Electricity production from renewable sources,...",1990,1.312012e+00,World
20,World,World,World,WLD,Income share held by lowest 10%,1990,NaN,World
21,World,World,World,WLD,Individuals using the Internet (% of population),1990,4.934308e-02,World
22,World,World,World,WLD,People using at least basic drinking water ser...,1990,NaN,World
23,World,World,World,WLD,People using at least basic drinking water ser...,1990,NaN,World
24,World,World,World,WLD,People using at least basic drinking water ser...,1990,NaN,World
25,World,World,World,WLD,People using at least basic sanitation service...,1990,NaN,World
26,World,World,World,WLD,People using at least basic sanitation service...,1990,NaN,World
27,World,World,World,WLD,People using at least basic sanitation service...,1990,NaN,World
28,World,World,World,WLD,People using safely managed drinking water ser...,1990,NaN,World
29,World,World,World,WLD,People using safely managed drinking water ser...,1990,NaN,World
...,...,...,...,...,...,...,...,...
256794,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, at least Master's or e...",2018,NaN,Africa
256795,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, Doctoral or equivalent...",2018,NaN,Africa
256796,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electric power consumption (kWh per capita),2018,NaN,Africa
256797,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from coal sources (% of...,2018,NaN,Africa
256798,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from hydroelectric sour...,2018,NaN,Africa
256799,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from natural gas source...,2018,NaN,Africa
256800,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from nuclear sources (%...,2018,NaN,Africa
256801,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from oil sources (% of ...,2018,NaN,Africa
256802,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Electricity production from renewable sources,...",2018,NaN,Africa
256803,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Income share held by lowest 10%,2018,NaN,Africa
256804,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Individuals using the Internet (% of population),2018,NaN,Africa
256805,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,NaN,Africa
256806,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,NaN,Africa
256807,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,NaN,Africa
256808,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,NaN,Africa
256809,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,NaN,Africa
256810,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,NaN,Africa
256811,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,2018,NaN,Africa
256812,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,2018,NaN,Africa
256813,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,2018,NaN,Africa
256814,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 0-14 (% of total),2018,NaN,Africa
256815,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, female (% of total)",2018,NaN,Africa
256816,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, male (% of total)",2018,NaN,Africa
256817,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, female (% of female pop...",2018,NaN,Africa
256818,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, male (% of male populat...",2018,NaN,Africa
256819,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 15-64 (% of total),2018,NaN,Africa
256820,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, female (% of female popul...",2018,NaN,Africa
256821,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, male (% of male population)",2018,NaN,Africa
256822,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 65 and above (% of total),2018,NaN,Africa
256823,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population, total",2018,NaN,Africa

In [15]:
consolidated['Value'] = consolidated.groupby(['Country Name','Indicator Name'])['Value'].ffill()
consolidated['Value'] = consolidated.groupby(['Country Name','Indicator Name'])['Value'].bfill()
consolidated

,Country Name,Region,Sub-region,Country Code,Indicator Name,Year,Value,Group
0,World,World,World,WLD,Access to clean fuels and technologies for coo...,1990,4.942793e+01,World
1,World,World,World,WLD,Access to electricity (% of population),1990,7.139056e+01,World
2,World,World,World,WLD,"Access to electricity, rural (% of rural popul...",1990,6.284804e+01,World
3,World,World,World,WLD,"Access to electricity, urban (% of urban popul...",1990,9.282149e+01,World
4,World,World,World,WLD,Adjusted net national income (current US$),1990,1.855646e+13,World
5,World,World,World,WLD,"Educational attainment, at least Bachelor's or...",1990,NaN,World
6,World,World,World,WLD,"Educational attainment, at least completed low...",1990,NaN,World
7,World,World,World,WLD,"Educational attainment, at least completed pos...",1990,NaN,World
8,World,World,World,WLD,"Educational attainment, at least completed pri...",1990,NaN,World
9,World,World,World,WLD,"Educational attainment, at least completed sho...",1990,NaN,World
10,World,World,World,WLD,"Educational attainment, at least completed upp...",1990,NaN,World
11,World,World,World,WLD,"Educational attainment, at least Master's or e...",1990,NaN,World
12,World,World,World,WLD,"Educational attainment, Doctoral or equivalent...",1990,NaN,World
13,World,World,World,WLD,Electric power consumption (kWh per capita),1990,2.124756e+03,World
14,World,World,World,WLD,Electricity production from coal sources (% of...,1990,3.700596e+01,World
15,World,World,World,WLD,Electricity production from hydroelectric sour...,1990,1.792874e+01,World
16,World,World,World,WLD,Electricity production from natural gas source...,1990,1.473076e+01,World
17,World,World,World,WLD,Electricity production from nuclear sources (%...,1990,1.692028e+01,World
18,World,World,World,WLD,Electricity production from oil sources (% of ...,1990,1.020776e+01,World
19,World,World,World,WLD,"Electricity production from renewable sources,...",1990,1.312012e+00,World
20,World,World,World,WLD,Income share held by lowest 10%,1990,NaN,World
21,World,World,World,WLD,Individuals using the Internet (% of population),1990,4.934308e-02,World
22,World,World,World,WLD,People using at least basic drinking water ser...,1990,8.001575e+01,World
23,World,World,World,WLD,People using at least basic drinking water ser...,1990,6.761005e+01,World
24,World,World,World,WLD,People using at least basic drinking water ser...,1990,9.521721e+01,World
25,World,World,World,WLD,People using at least basic sanitation service...,1990,5.801061e+01,World
26,World,World,World,WLD,People using at least basic sanitation service...,1990,3.815437e+01,World
27,World,World,World,WLD,People using at least basic sanitation service...,1990,7.826654e+01,World
28,World,World,World,WLD,People using safely managed drinking water ser...,1990,6.142000e+01,World
29,World,World,World,WLD,People using safely managed drinking water ser...,1990,4.095000e+01,World
...,...,...,...,...,...,...,...,...
256794,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, at least Master's or e...",2018,NaN,Africa
256795,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, Doctoral or equivalent...",2018,NaN,Africa
256796,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electric power consumption (kWh per capita),2018,5.369955e+02,Africa
256797,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from coal sources (% of...,2018,4.678134e+01,Africa
256798,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from hydroelectric sour...,2018,5.139561e+01,Africa
256799,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from natural gas source...,2018,0.000000e+00,Africa
256800,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from nuclear sources (%...,2018,0.000000e+00,Africa
256801,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from oil sources (% of ...,2018,4.943867e-01,Africa
256802,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Electricity production from renewable sources,...",2018,1.328664e+00,Africa
256803,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Income share held by lowest 10%,2018,2.500000e+00,Africa
256804,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Individuals using the Internet (% of population),2018,2.705549e+01,Africa
256805,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,6.656310e+01,Africa
256806,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,5.353470e+01,Africa
256807,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,9.377563e+01,Africa
256808,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,3.858862e+01,Africa
256809,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,3.124219e+01,Africa
256810,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,5.393317e+01,Africa
256811,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,2018,NaN,Africa
256812,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,2018,NaN,Africa
256813,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using safely managed drinking water ser...,2018,NaN,Africa
256814,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 0-14 (% of total),2018,4.120489e+01,Africa
256815,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, female (% of total)",2018,4.003326e+01,Africa
256816,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, male (% of total)",2018,4.243784e+01,Africa
256817,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, female (% of female pop...",2018,1.156224e+01,Africa
256818,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, male (% of male populat...",2018,1.221913e+01,Africa
256819,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 15-64 (% of total),2018,5.597321e+01,Africa
256820,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, female (% of female popul...",2018,1.351151e+01,Africa
256821,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, male (% of male population)",2018,1.431693e+01,Africa
256822,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 65 and above (% of total),2018,2.821904e+00,Africa
256823,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population, total",2018,1.652990e+07,Africa

In [16]:
consolidated.to_csv('historical_world_data.csv')
consolidated['Group'].unique()

array(['World', 'Asia', 'Europe', 'Africa', 'Oceania', 'Americas',
       'Bangladesh'], dtype=object)

In [17]:
indicators_list_1 = {'Bangladesh'}
Bangladesh_all = consolidated[consolidated['Country Name'].isin(indicators_list_1)]
Bangladesh_all

,Country Name,Region,Sub-region,Country Code,Indicator Name,Year,Value,Group
656,Bangladesh,Asia,Southern Asia,BGD,Access to clean fuels and technologies for coo...,1990,7.240000e+00,Bangladesh
657,Bangladesh,Asia,Southern Asia,BGD,Access to electricity (% of population),1990,8.544374e+00,Bangladesh
658,Bangladesh,Asia,Southern Asia,BGD,"Access to electricity, rural (% of rural popul...",1990,4.570000e+00,Bangladesh
659,Bangladesh,Asia,Southern Asia,BGD,"Access to electricity, urban (% of urban popul...",1990,6.598398e+01,Bangladesh
660,Bangladesh,Asia,Southern Asia,BGD,Adjusted net national income (current US$),1990,2.961164e+10,Bangladesh
661,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, at least Bachelor's or...",1990,5.693860e+00,Bangladesh
662,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, at least completed low...",1990,2.671473e+01,Bangladesh
663,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, at least completed pos...",1990,4.208650e+00,Bangladesh
664,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, at least completed pri...",1990,4.724151e+01,Bangladesh
665,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, at least completed sho...",1990,4.208650e+00,Bangladesh
666,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, at least completed upp...",1990,1.712843e+01,Bangladesh
667,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, at least Master's or e...",1990,1.681700e+00,Bangladesh
668,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, Doctoral or equivalent...",1990,7.955000e-02,Bangladesh
669,Bangladesh,Asia,Southern Asia,BGD,Electric power consumption (kWh per capita),1990,4.836675e+01,Bangladesh
670,Bangladesh,Asia,Southern Asia,BGD,Electricity production from coal sources (% of...,1990,0.000000e+00,Bangladesh
671,Bangladesh,Asia,Southern Asia,BGD,Electricity production from hydroelectric sour...,1990,1.143301e+01,Bangladesh
672,Bangladesh,Asia,Southern Asia,BGD,Electricity production from natural gas source...,1990,8.426022e+01,Bangladesh
673,Bangladesh,Asia,Southern Asia,BGD,Electricity production from nuclear sources (%...,1990,0.000000e+00,Bangladesh
674,Bangladesh,Asia,Southern Asia,BGD,Electricity production from oil sources (% of ...,1990,4.306777e+00,Bangladesh
675,Bangladesh,Asia,Southern Asia,BGD,"Electricity production from renewable sources,...",1990,0.000000e+00,Bangladesh
676,Bangladesh,Asia,Southern Asia,BGD,Income share held by lowest 10%,1990,4.100000e+00,Bangladesh
677,Bangladesh,Asia,Southern Asia,BGD,Individuals using the Internet (% of population),1990,0.000000e+00,Bangladesh
678,Bangladesh,Asia,Southern Asia,BGD,People using at least basic drinking water ser...,1990,9.464647e+01,Bangladesh
679,Bangladesh,Asia,Southern Asia,BGD,People using at least basic drinking water ser...,1990,9.365725e+01,Bangladesh
680,Bangladesh,Asia,Southern Asia,BGD,People using at least basic drinking water ser...,1990,9.785066e+01,Bangladesh
681,Bangladesh,Asia,Southern Asia,BGD,People using at least basic sanitation service...,1990,2.534632e+01,Bangladesh
682,Bangladesh,Asia,Southern Asia,BGD,People using at least basic sanitation service...,1990,2.059161e+01,Bangladesh
683,Bangladesh,Asia,Southern Asia,BGD,People using at least basic sanitation service...,1990,4.074723e+01,Bangladesh
684,Bangladesh,Asia,Southern Asia,BGD,People using safely managed drinking water ser...,1990,5.585231e+01,Bangladesh
685,Bangladesh,Asia,Southern Asia,BGD,People using safely managed drinking water ser...,1990,5.934554e+01,Bangladesh
...,...,...,...,...,...,...,...,...
248635,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, at least Master's or e...",2018,3.481190e+00,Bangladesh
248636,Bangladesh,Asia,Southern Asia,BGD,"Educational attainment, Doctoral or equivalent...",2018,1.659600e-01,Bangladesh
248637,Bangladesh,Asia,Southern Asia,BGD,Electric power consumption (kWh per capita),2018,3.103912e+02,Bangladesh
248638,Bangladesh,Asia,Southern Asia,BGD,Electricity production from coal sources (% of...,2018,1.689516e+00,Bangladesh
248639,Bangladesh,Asia,Southern Asia,BGD,Electricity production from hydroelectric sour...,2018,9.591432e-01,Bangladesh
248640,Bangladesh,Asia,Southern Asia,BGD,Electricity production from natural gas source...,2018,8.070360e+01,Bangladesh
248641,Bangladesh,Asia,Southern Asia,BGD,Electricity production from nuclear sources (%...,2018,0.000000e+00,Bangladesh
248642,Bangladesh,Asia,Southern Asia,BGD,Electricity production from oil sources (% of ...,2018,1.638000e+01,Bangladesh
248643,Bangladesh,Asia,Southern Asia,BGD,"Electricity production from renewable sources,...",2018,2.677467e-01,Bangladesh
248644,Bangladesh,Asia,Southern Asia,BGD,Income share held by lowest 10%,2018,3.700000e+00,Bangladesh
248645,Bangladesh,Asia,Southern Asia,BGD,Individuals using the Internet (% of population),2018,1.802000e+01,Bangladesh
248646,Bangladesh,Asia,Southern Asia,BGD,People using at least basic drinking water ser...,2018,9.732714e+01,Bangladesh
248647,Bangladesh,Asia,Southern Asia,BGD,People using at least basic drinking water ser...,2018,9.695907e+01,Bangladesh
248648,Bangladesh,Asia,Southern Asia,BGD,People using at least basic drinking water ser...,2018,9.803290e+01,Bangladesh
248649,Bangladesh,Asia,Southern Asia,BGD,People using at least basic sanitation service...,2018,4.692459e+01,Bangladesh
248650,Bangladesh,Asia,Southern Asia,BGD,People using at least basic sanitation service...,2018,4.340900e+01,Bangladesh
248651,Bangladesh,Asia,Southern Asia,BGD,People using at least basic sanitation service...,2018,5.366542e+01,Bangladesh
248652,Bangladesh,Asia,Southern Asia,BGD,People using safely managed drinking water ser...,2018,5.567325e+01,Bangladesh
248653,Bangladesh,Asia,Southern Asia,BGD,People using safely managed drinking water ser...,2018,6.143772e+01,Bangladesh
248654,Bangladesh,Asia,Southern Asia,BGD,People using safely managed drinking water ser...,2018,4.462040e+01,Bangladesh
248655,Bangladesh,Asia,Southern Asia,BGD,Population ages 0-14 (% of total),2018,2.836997e+01,Bangladesh
248656,Bangladesh,Asia,Southern Asia,BGD,"Population ages 0-14, female (% of total)",2018,2.799292e+01,Bangladesh
248657,Bangladesh,Asia,Southern Asia,BGD,"Population ages 0-14, male (% of total)",2018,2.874068e+01,Bangladesh
248658,Bangladesh,Asia,Southern Asia,BGD,"Population ages 10-14, female (% of female pop...",2018,9.668378e+00,Bangladesh
248659,Bangladesh,Asia,Southern Asia,BGD,"Population ages 10-14, male (% of male populat...",2018,9.934751e+00,Bangladesh
248660,Bangladesh,Asia,Southern Asia,BGD,Population ages 15-64 (% of total),2018,6.653180e+01,Bangladesh
248661,Bangladesh,Asia,Southern Asia,BGD,"Population ages 5-9, female (% of female popul...",2018,9.236457e+00,Bangladesh
248662,Bangladesh,Asia,Southern Asia,BGD,"Population ages 5-9, male (% of male population)",2018,9.475235e+00,Bangladesh
248663,Bangladesh,Asia,Southern Asia,BGD,Population ages 65 and above (% of total),2018,5.098227e+00,Bangladesh
248664,Bangladesh,Asia,Southern Asia,BGD,"Population, total",2018,1.646698e+08,Bangladesh

In [18]:
Bangladesh_all = Bangladesh_all.pivot(index='Year', columns='Indicator Name', values='Value')
Bangladesh_all.reset_index(level=0, inplace=True)
Bangladesh_all

Indicator Name,Year,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Adjusted net national income (current US$),"Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)","Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)","Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)","Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)",...,Population ages 0-14 (% of total),"Population ages 0-14, female (% of total)","Population ages 0-14, male (% of total)","Population ages 10-14, female (% of female population)","Population ages 10-14, male (% of male population)",Population ages 15-64 (% of total),"Population ages 5-9, female (% of female population)","Population ages 5-9, male (% of male population)",Population ages 65 and above (% of total),"Population, total"
0,1990,7.24,8.544374,4.570000,65.983978,2.961164e+10,0.07955,5.69386,1.68170,26.71473,...,42.333236,42.483007,42.189957,12.699226,12.595682,54.544091,14.221091,14.150245,3.122673,106188642.0
1,1991,7.24,14.290000,4.570000,58.060595,2.905195e+10,0.07955,5.69386,1.68170,26.71473,...,41.959662,42.105717,41.819836,12.696224,12.585999,54.863345,14.103654,14.051432,3.176993,108727432.0
2,1992,7.24,13.444250,4.570000,68.116959,2.980882e+10,0.07955,5.69386,1.68170,26.71473,...,41.513171,41.642028,41.389767,12.674624,12.574943,55.258636,13.976040,13.932909,3.228193,111221938.0
3,1993,7.24,15.890874,1.753809,69.182335,3.130206e+10,0.07955,5.69386,1.68170,26.71473,...,41.010199,41.113745,40.911000,12.639215,12.563417,55.712824,13.828400,13.784959,3.276977,113695139.0
4,1994,7.24,17.800000,10.400000,75.200000,3.199234e+10,0.07955,5.69386,1.68170,26.71473,...,40.476224,40.554765,40.400958,12.593746,12.545132,56.200208,13.651162,13.604089,3.323567,116182267.0
5,1995,7.24,20.762709,6.760987,71.305870,3.591632e+10,0.07955,5.69386,1.68170,26.71473,...,39.925996,39.984355,39.870052,12.534576,12.507109,56.705071,13.437708,13.391989,3.368933,118706871.0
6,1996,7.24,23.181799,9.258692,72.361969,4.377163e+10,0.07955,5.69386,1.68170,26.71473,...,39.383744,39.425861,39.343361,12.445654,12.431195,57.150801,13.245270,13.201854,3.465455,121269645.0
7,1997,7.24,22.400000,15.100000,79.500000,4.562402e+10,0.07955,5.69386,1.68170,26.71473,...,38.824538,38.856326,38.794052,12.343230,12.334170,57.617459,13.034435,12.996814,3.558003,123854640.0
8,1998,7.24,27.971037,14.227780,74.457672,4.728145e+10,0.07955,5.69386,1.68170,26.71473,...,38.251055,38.277163,38.226010,12.230813,12.220679,58.100530,12.805476,12.777054,3.648415,126447965.0
9,1999,7.24,30.335066,16.691406,75.495216,4.859716e+10,0.07955,5.69386,1.68170,26.71473,...,37.662360,37.683775,37.641814,12.107198,12.094497,58.598854,12.566262,12.548005,3.738786,129029691.0
10,2000,7.24,32.000000,20.500000,81.200000,5.065945e+10,0.07955,5.69386,1.68170,26.71473,...,37.060570,37.075983,37.045774,11.966357,11.954171,59.108765,12.327317,12.316860,3.830665,131581243.0
11,2001,7.78,34.998806,21.490879,77.549675,5.107515e+10,0.07955,5.69386,1.68170,26.71473,...,36.565564,36.562590,36.568415,11.804966,11.806769,59.511381,12.146757,12.147024,3.923055,134107160.0
12,2002,8.16,37.309124,23.733379,78.571579,5.225685e+10,0.07955,5.69386,1.68170,26.71473,...,36.051200,36.030114,36.071465,11.643710,11.659583,59.939419,11.984043,11.993851,4.009381,136600667.0
13,2003,8.73,39.613159,25.979646,79.593681,5.746722e+10,0.07955,5.69386,1.68170,26.71473,...,35.523807,35.486485,35.559713,11.488581,11.514112,60.383896,11.831889,11.851426,4.092297,139019001.0
14,2004,9.20,40.600000,30.400000,76.600000,6.244530e+10,0.07955,5.69386,1.68170,26.71473,...,34.987393,34.936308,35.036576,11.345580,11.376310,60.837297,11.679214,11.708843,4.175310,141307489.0
15,2005,9.74,44.230000,31.190000,82.610000,6.661527e+10,0.07955,5.69386,1.68170,26.71473,...,34.440488,34.377413,34.501261,11.216380,11.250873,61.299037,11.512170,11.551711,4.260476,143431101.0
16,2006,10.36,50.525102,38.845318,77.799135,6.887572e+10,0.07955,5.69386,1.68170,26.71473,...,33.996681,33.882862,34.106669,11.074724,11.139725,61.637795,11.379317,11.453698,4.365524,145368004.0
17,2007,10.92,46.500000,36.600000,82.100000,7.702492e+10,0.07955,5.69386,1.68170,26.71473,...,33.534377,33.368951,33.694707,10.960727,11.062032,62.001641,11.251806,11.359379,4.463982,147139191.0
18,2008,11.59,51.249775,37.565392,84.805046,8.989812e+10,0.07955,5.69386,1.68170,26.71473,...,33.060485,32.847023,33.267972,10.872641,11.006979,62.386564,11.117134,11.257059,4.552951,148805814.0
19,2009,12.20,53.632854,40.002460,85.882141,1.011555e+11,0.07955,5.69386,1.68170,26.71473,...,32.585715,32.328683,32.836261,10.798535,10.961137,62.785568,10.964452,11.135179,4.628717,150454708.0
20,2010,12.90,55.260000,42.490000,90.100000,1.139067e+11,0.07955,5.69386,1.68170,26.71473,...,32.114039,31.816352,32.405020,10.723850,10.913443,63.196428,10.785448,10.984092,4.689533,152149102.0
21,2011,13.63,59.600000,49.300000,90.200000,1.261392e+11,0.07955,5.69386,1.68170,35.29797,...,31.545717,31.228111,31.856451,10.602374,10.813966,63.664579,10.589986,10.798820,4.789704,153911916.0
22,2012,14.33,60.878216,47.570292,89.170555,1.317397e+11,0.08145,5.87042,1.72566,36.04574,...,31.005985,30.670960,31.334051,10.477476,10.709776,64.114479,10.369402,10.585449,4.879536,155727053.0
23,2013,15.06,61.500000,54.200000,88.000000,1.474090e+11,0.09163,5.50232,1.96671,33.70535,...,30.482135,30.134217,30.823120,10.354242,10.599831,64.563079,10.124554,10.346599,4.954786,157571292.0
24,2014,15.96,62.400000,51.400000,90.700000,1.671869e+11,0.09679,5.85214,2.05822,34.91573,...,29.956213,29.600091,30.305538,10.227118,10.478215,65.035426,9.871318,10.098337,5.008360,159405279.0
25,2015,16.68,68.204681,55.530021,92.507179,1.894934e+11,0.15837,8.23714,3.32594,40.84080,...,29.421802,29.060613,29.776396,10.082357,10.334984,65.540029,9.633034,9.863433,5.038169,161200886.0
26,2016,17.72,75.920000,68.850000,94.010000,2.136066e+11,0.16596,8.50960,3.48119,41.50080,...,28.900854,28.531355,29.263876,9.883229,10.141884,66.021669,9.418914,9.653836,5.077478,162951560.0
27,2017,17.72,75.920000,68.850000,94.010000,2.369246e+11,0.16596,8.50960,3.48119,41.50080,...,28.369972,27.992920,28.740679,9.668378,9.934751,66.531802,9.236457,9.475235,5.098227,164669751.0
28,2018,17.72,75.920000,68.850000,94.010000,2.369246e+11,0.16596,8.50960,3.48119,41.50080,...,28.369972,27.992920,28.740679,9.668378,9.934751,66.531802,9.236457,9.475235,5.098227,164669751.0

In [19]:
Bangladesh_all.to_csv('historical_bangladesh_data.csv')

In [20]:
consolidated = consolidated.dropna(subset=['Value'])
#consolidated = consolidated.groupby(['Country Name','Indicator Name'], sort=False)['Year'].max()
#consolidated
idx = consolidated.groupby(['Country Name','Indicator Name'])['Year'].transform(max) == consolidated['Year']
consolidated = consolidated[idx]
consolidated = consolidated.sort_values(['Country Name', 'Indicator Name'], ascending=[True, True])
consolidated

,Country Name,Region,Sub-region,Country Code,Indicator Name,Year,Value,Group
248009,Afghanistan,Asia,Southern Asia,AFG,Access to clean fuels and technologies for coo...,2018,3.244000e+01,Asia
248010,Afghanistan,Asia,Southern Asia,AFG,Access to electricity (% of population),2018,8.413714e+01,Asia
248011,Afghanistan,Asia,Southern Asia,AFG,"Access to electricity, rural (% of rural popul...",2018,7.896107e+01,Asia
248012,Afghanistan,Asia,Southern Asia,AFG,"Access to electricity, urban (% of urban popul...",2018,9.803841e+01,Asia
248013,Afghanistan,Asia,Southern Asia,AFG,Adjusted net national income (current US$),2018,1.691699e+10,Asia
248030,Afghanistan,Asia,Southern Asia,AFG,Individuals using the Internet (% of population),2018,1.144769e+01,Asia
248031,Afghanistan,Asia,Southern Asia,AFG,People using at least basic drinking water ser...,2018,6.298021e+01,Asia
248032,Afghanistan,Asia,Southern Asia,AFG,People using at least basic drinking water ser...,2018,5.348316e+01,Asia
248033,Afghanistan,Asia,Southern Asia,AFG,People using at least basic drinking water ser...,2018,8.904863e+01,Asia
248034,Afghanistan,Asia,Southern Asia,AFG,People using at least basic sanitation service...,2018,3.922043e+01,Asia
248035,Afghanistan,Asia,Southern Asia,AFG,People using at least basic sanitation service...,2018,3.295999e+01,Asia
248036,Afghanistan,Asia,Southern Asia,AFG,People using at least basic sanitation service...,2018,5.640471e+01,Asia
248040,Afghanistan,Asia,Southern Asia,AFG,Population ages 0-14 (% of total),2018,4.324456e+01,Asia
248041,Afghanistan,Asia,Southern Asia,AFG,"Population ages 0-14, female (% of total)",2018,4.344326e+01,Asia
248042,Afghanistan,Asia,Southern Asia,AFG,"Population ages 0-14, male (% of total)",2018,4.305752e+01,Asia
248043,Afghanistan,Asia,Southern Asia,AFG,"Population ages 10-14, female (% of female pop...",2018,1.376510e+01,Asia
248044,Afghanistan,Asia,Southern Asia,AFG,"Population ages 10-14, male (% of male populat...",2018,1.365012e+01,Asia
248045,Afghanistan,Asia,Southern Asia,AFG,Population ages 15-64 (% of total),2018,5.417491e+01,Asia
248046,Afghanistan,Asia,Southern Asia,AFG,"Population ages 5-9, female (% of female popul...",2018,1.479725e+01,Asia
248047,Afghanistan,Asia,Southern Asia,AFG,"Population ages 5-9, male (% of male population)",2018,1.461356e+01,Asia
248048,Afghanistan,Asia,Southern Asia,AFG,Population ages 65 and above (% of total),2018,2.580526e+00,Asia
248049,Afghanistan,Asia,Southern Asia,AFG,"Population, total",2018,3.553008e+07,Asia
248050,Albania,Europe,Southern Europe,ALB,Access to clean fuels and technologies for coo...,2018,7.742000e+01,Europe
248051,Albania,Europe,Southern Europe,ALB,Access to electricity (% of population),2018,1.000000e+02,Europe
248052,Albania,Europe,Southern Europe,ALB,"Access to electricity, rural (% of rural popul...",2018,1.000000e+02,Europe
248053,Albania,Europe,Southern Europe,ALB,"Access to electricity, urban (% of urban popul...",2018,1.000000e+02,Europe
248054,Albania,Europe,Southern Europe,ALB,Adjusted net national income (current US$),2018,1.179597e+10,Europe
248062,Albania,Europe,Southern Europe,ALB,"Educational attainment, Doctoral or equivalent...",2018,8.962000e-02,Europe
248055,Albania,Europe,Southern Europe,ALB,"Educational attainment, at least Bachelor's or...",2018,1.289966e+01,Europe
248061,Albania,Europe,Southern Europe,ALB,"Educational attainment, at least Master's or e...",2018,1.233073e+01,Europe
...,...,...,...,...,...,...,...,...
256789,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, at least completed low...",2018,5.876317e+01,Africa
256790,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, at least completed pos...",2018,1.305274e+01,Africa
256791,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, at least completed pri...",2018,7.578488e+01,Africa
256792,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, at least completed sho...",2018,3.399720e+00,Africa
256793,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Educational attainment, at least completed upp...",2018,1.519199e+01,Africa
256796,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electric power consumption (kWh per capita),2018,5.369955e+02,Africa
256797,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from coal sources (% of...,2018,4.678134e+01,Africa
256798,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from hydroelectric sour...,2018,5.139561e+01,Africa
256799,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from natural gas source...,2018,0.000000e+00,Africa
256800,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from nuclear sources (%...,2018,0.000000e+00,Africa
256801,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Electricity production from oil sources (% of ...,2018,4.943867e-01,Africa
256802,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Electricity production from renewable sources,...",2018,1.328664e+00,Africa
256803,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Income share held by lowest 10%,2018,2.500000e+00,Africa
256804,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Individuals using the Internet (% of population),2018,2.705549e+01,Africa
256805,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,6.656310e+01,Africa
256806,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,5.353470e+01,Africa
256807,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic drinking water ser...,2018,9.377563e+01,Africa
256808,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,3.858862e+01,Africa
256809,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,3.124219e+01,Africa
256810,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,People using at least basic sanitation service...,2018,5.393317e+01,Africa
256814,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 0-14 (% of total),2018,4.120489e+01,Africa
256815,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, female (% of total)",2018,4.003326e+01,Africa
256816,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 0-14, male (% of total)",2018,4.243784e+01,Africa
256817,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, female (% of female pop...",2018,1.156224e+01,Africa
256818,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 10-14, male (% of male populat...",2018,1.221913e+01,Africa
256819,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 15-64 (% of total),2018,5.597321e+01,Africa
256820,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, female (% of female popul...",2018,1.351151e+01,Africa
256821,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population ages 5-9, male (% of male population)",2018,1.431693e+01,Africa
256822,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,Population ages 65 and above (% of total),2018,2.821904e+00,Africa
256823,Zimbabwe,Africa,Sub-Saharan Africa,ZWE,"Population, total",2018,1.652990e+07,Africa

In [21]:
consolidated.to_csv('world_data.csv')

In [22]:
chars_data.head()

,Division,zila,upazila,union,Administrative Unit Residence Community,Area (in Acres),Number of Household,Population All Ages Both Sex,Population All Ages Male,Population All Ages Female,...,Population Aged 10-14 Years Both Sex,Population Aged 10-14 Years Male,Population Aged 10-14 Years Female,Population Aged 18 Years+ Both Sex,Population Aged 18 Years+ Male,Population Aged 18 Years+ Female,Literacy Rate 7 Years + Both Sex,Literacy Rate 7 Years + Male,Literacy Rate 7 Years + Female,Married Women Aged 15-49 Years
0,10,4,28,38,Burir Char union,8661,6949,29542,14561,14981,...,3338,1814,1524,18424,8734,9690,49.8,51.5,48.3,7784
1,10,4,85,11,Char Duanti union,8921,6576,24563,12247,12316,...,2681,1417,1264,15498,7482,8016,54.2,53.1,55.3,6428
2,10,6,7,20,Char Amaddi union,6001,3985,18122,8568,9554,...,2383,1195,1188,10637,4777,5860,69.0,68.8,69.1,4496
3,10,6,51,34,Char Baria union,4860,4736,22904,11510,11394,...,2822,1485,1337,14475,7119,7356,62.9,63.2,62.5,5402
4,10,6,51,43,Char Kowa union,9346,6479,30232,15078,15154,...,3744,1916,1828,18334,8934,9400,59.7,60.7,58.7,7263

In [23]:
total_chars = chars_data['Population All Ages Both Sex'].sum(skipna = True) 
total_chars
chars_energy_access = 42

In [24]:
#world population
p_world_i = consolidated[consolidated['Indicator Name'] == 'Population, total']
p_asia_i = p_world_i[p_world_i['Region'] == 'Asia']
p_bangladesh_i = p_asia_i[p_asia_i['Country Name'] == 'Bangladesh']

#energy access
a_world_i = consolidated[consolidated['Indicator Name'] == 'Access to electricity (% of population)']
a_asia_i = a_world_i[a_world_i['Region'] == 'Asia']
a_bangladesh_i = a_asia_i[a_asia_i['Country Name'] == 'Bangladesh']
r_access = consolidated[consolidated['Indicator Name'] == 'Access to electricity, rural (% of rural population)']
a_chars_i = r_access[r_access['Country Name'] == 'Bangladesh']

#power consumption
pc_world_i = consolidated[consolidated['Indicator Name'] == 'Electric power consumption (kWh per capita)']
pc_asia_i = pc_world_i[pc_world_i['Region'] == 'Asia']
pc_bangladesh_i = pc_asia_i[pc_asia_i['Country Name'] == 'Bangladesh']

#energy sources
es_world_coal = consolidated[consolidated['Indicator Name'] == 'Electricity production from coal sources (% of total)']
es_asia_coal = es_world_coal[es_world_coal['Region'] == 'Asia']
es_bangladesh_coal = es_asia_coal[es_asia_coal['Country Name'] == 'Bangladesh']

es_world_hydro = consolidated[consolidated['Indicator Name'] == 'Electricity production from hydroelectric sources (% of total)']
es_asia_hydro = es_world_hydro[es_world_hydro['Region'] == 'Asia']
es_bangladesh_hydro = es_asia_hydro[es_asia_hydro['Country Name'] == 'Bangladesh']

es_world_gas = consolidated[consolidated['Indicator Name'] == 'Electricity production from natural gas sources (% of total)']
es_asia_gas = es_world_gas[es_world_gas['Region'] == 'Asia']
es_bangladesh_gas = es_asia_gas[es_asia_gas['Country Name'] == 'Bangladesh']

es_world_nuclear = consolidated[consolidated['Indicator Name'] == 'Electricity production from nuclear sources (% of total)']
es_asia_nuclear = es_world_nuclear[es_world_nuclear['Region'] == 'Asia']
es_bangladesh_nuclear = es_asia_nuclear[es_asia_nuclear['Country Name'] == 'Bangladesh']

es_world_oil = consolidated[consolidated['Indicator Name'] == 'Electricity production from oil sources (% of total)']
es_asia_oil = es_world_oil[es_world_oil['Region'] == 'Asia']
es_bangladesh_oil = es_asia_oil[es_asia_oil['Country Name'] == 'Bangladesh']

es_world_renewable = consolidated[consolidated['Indicator Name'] == 'Electricity production from renewable sources, excluding hydroelectric (% of total)']
es_asia_renewable = es_world_renewable[es_world_renewable['Region'] == 'Asia']
es_bangladesh_renewable = es_asia_renewable[es_asia_renewable['Country Name'] == 'Bangladesh']

#extreme weather
ex_world_i = consolidated[consolidated['Indicator Name'] == 'Droughts, floods, extreme temperatures (% of population, average 1990-2009)']
ex_asia_i = ex_world_i[ex_world_i['Region'] == 'Asia']
ex_bangladesh_i = ex_asia_i[ex_asia_i['Country Name'] == 'Bangladesh']

#internet usage
i_world_i = consolidated[consolidated['Indicator Name'] == 'Individuals using the Internet (% of population)']
i_asia_i = i_world_i[i_world_i['Region'] == 'Asia']
i_bangladesh_i = i_asia_i[i_asia_i['Country Name'] == 'Bangladesh']

#mortality
m_world_pollution = consolidated[consolidated['Indicator Name'] == 'Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)']
m_asia_pollution = m_world_pollution[m_world_pollution['Region'] == 'Asia']
m_bangladesh_pollution = m_asia_pollution[m_asia_pollution['Country Name'] == 'Bangladesh']

m_world_water = consolidated[consolidated['Indicator Name'] == 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)']
m_asia_water = m_world_water[m_world_water['Region'] == 'Asia']
m_bangladesh_water = m_asia_water[m_asia_water['Country Name'] == 'Bangladesh']

#water access
w_world_i = consolidated[consolidated['Indicator Name'] == 'People using safely managed drinking water services (% of population)']
w_asia_i = w_world_i[w_world_i['Region'] == 'Asia']
w_bangladesh_i = w_asia_i[w_asia_i['Country Name'] == 'Bangladesh']
r_water = consolidated[consolidated['Indicator Name'] == 'People using safely managed drinking water services, rural (% of rural population)']
w_chars_i = r_water[r_water['Country Name'] == 'Bangladesh']

In [25]:
world_total_population = p_world_i['Value'].sum()
asia_total_population = p_asia_i['Value'].sum()
bangladesh_total_population = p_bangladesh_i['Value'].sum()

avg_world_energy_access = a_world_i['Value'].mean()
avg_asia_energy_access = a_asia_i['Value'].mean()
bangladesh_energy_access = a_bangladesh_i['Value'].sum()
chars_energy_access = a_chars_i['Value'].sum()

avg_world_power_consumption = pc_world_i['Value'].mean()
avg_asia_power_consumption = pc_asia_i['Value'].mean()
bangladesh_power_consumption = pc_bangladesh_i['Value'].sum()

#energy sources
world_coal = es_world_coal['Value'].mean()
asia_coal = es_asia_coal['Value'].mean()
bangladesh_coal = es_bangladesh_coal['Value'].mean()

world_hydro = es_world_hydro['Value'].mean()
asia_hydro = es_asia_hydro['Value'].mean()
bangladesh_hydro = es_bangladesh_hydro['Value'].mean()

world_gas = es_world_gas['Value'].mean()
asia_gas = es_asia_gas['Value'].mean()
bangladesh_gas = es_bangladesh_gas['Value'].mean()

world_nuclear = es_world_nuclear['Value'].mean()
asia_nuclear = es_asia_nuclear['Value'].mean()
bangladesh_nuclear = es_bangladesh_nuclear['Value'].mean()

world_oil = es_world_oil['Value'].mean()
asia_oil = es_asia_oil['Value'].mean()
bangladesh_oil = es_bangladesh_oil['Value'].mean()

world_renewable = es_world_renewable['Value'].mean()
asia_renewable = es_asia_renewable['Value'].mean()
bangladesh_renewable = es_bangladesh_renewable['Value'].mean()

#extreme weather
extreme_world = ex_world_i['Value'].mean()
extreme_asia = ex_asia_i['Value'].mean()
extreme_bangladesh = ex_bangladesh_i['Value'].mean()

#internet usage
internet_world = i_world_i['Value'].mean()
internet_asia = i_asia_i['Value'].mean()
internet_bangladesh = i_bangladesh_i['Value'].mean()

#mortality
mortality_pollution_world = m_world_pollution['Value'].mean()/100000
mortality_pollution_asia = m_asia_pollution['Value'].mean()/100000
mortality_pollution_bangladesh = m_bangladesh_pollution['Value'].mean()/100000

mortality_world_water = m_world_water['Value'].mean()/100000
mortality_asia_water = m_asia_water['Value'].mean()/100000
mortality_bangladesh_water = m_bangladesh_water['Value'].mean()/100000

#water access
world_water_access = w_world_i['Value'].mean()
asia_water_access = w_asia_i['Value'].mean()
bangladesh_water_access = w_bangladesh_i['Value'].sum()
chars_water_access = w_chars_i['Value'].sum()

In [26]:
#summary dataset
data = np.array([['Indicator','Section','Value'],
                 #population
                 ['Population','World',world_total_population],
                 ['Population','Asia',asia_total_population],
                 ['Population','Bangladesh',bangladesh_total_population],
                 ['Population','Chars',total_chars],
                 #electricity access
                 ['Access to electricity','World',avg_world_energy_access],
                 ['Access to electricity','Asia',avg_asia_energy_access],
                 ['Access to electricity','Bangladesh',bangladesh_energy_access],
                 ['Access to electricity','Bangladesh',chars_energy_access],
                 #electricity consumption
                 ['Electric power consumption','World',avg_world_power_consumption],
                 ['Electric power consumption','Asia',avg_asia_power_consumption],
                 ['Electric power consumption','Bangladesh',bangladesh_power_consumption],
                 #energy sources
                 ['Coal','World',world_coal],
                 ['Coal','Asia',asia_coal],
                 ['Coal','Bangladesh',bangladesh_coal],
                 
                 ['Hydro','World',world_hydro],
                 ['Hydro','Asia',asia_hydro],
                 ['Hydro','Bangladesh',bangladesh_hydro],
                 
                 ['Gas','World',world_gas],
                 ['Gas','Asia',asia_gas],
                 ['Gas','Bangladesh',bangladesh_gas],
                 
                 ['Nuclear','World',world_nuclear],
                 ['Nuclear','Asia',asia_nuclear],
                 ['Nuclear','Bangladesh',bangladesh_nuclear],
                 
                 ['Oil','World',world_oil],
                 ['Oil','Asia',asia_oil],
                 ['Oil','Bangladesh',bangladesh_oil],
                 
                 ['Renewable','World',world_renewable],
                 ['Renewable','Asia',asia_renewable],
                 ['Renewable','Bangladesh',bangladesh_renewable],
                 #extreme weather
                 ['Population affected by extreme weather','World',extreme_world],
                 ['Population affected by extreme weather','Asia',extreme_asia],
                 ['Population affected by extreme weather','Bangladesh',extreme_bangladesh],
                 #internet usage
                 ['Internet usage','World',internet_world],
                 ['Internet usage','Asia',internet_asia],
                 ['Internet usage','Bangladesh',internet_bangladesh],
                 #mortality
                 ['Pollution Mortality','World',mortality_pollution_world],
                 ['Pollution Mortality','Asia',mortality_pollution_asia],
                 ['Pollution Mortality','Bangladesh',mortality_pollution_bangladesh],
                 
                 ['Unsafe water mortality','World',mortality_world_water],
                 ['Unsafe water mortality','Asia',mortality_asia_water],
                 ['Unsafe water mortality','Bangladesh',mortality_bangladesh_water],
                 #water access
                 ['Water access','World',world_water_access],
                 ['Water access','Asia',asia_water_access],
                 ['Water access','Bangladesh',bangladesh_water_access],
                 ['Water access','Chars',chars_water_access]])

In [27]:
summary = pd.DataFrame(data=data[1:,:], columns=data[0,0:])
summary

                                 Indicator     Section               Value
0                               Population       World       15033296149.0
1                               Population        Asia        4458423254.0
2                               Population  Bangladesh         164669751.0
3                               Population       Chars             4243862
4                    Access to electricity       World   83.64814352346181
5                    Access to electricity        Asia   93.37097797851563
6                    Access to electricity  Bangladesh               75.92
7                    Access to electricity  Bangladesh               68.85
8               Electric power consumption       World   4243.462742451758
9               Electric power consumption        Asia   4272.969487730684
10              Electric power consumption  Bangladesh  310.39122612746104
11                                    Coal       World  16.646783948534782
12                                    Coal        Asia  19.648499358904232
13                                    Coal  Bangladesh     1.6895155140567
14                                   Hydro       World  26.749102264362687
15                                   Hydro        Asia   19.11791265772623
16                                   Hydro  Bangladesh   0.959143210587856
17                                     Gas       World   27.01592349035792
18                                     Gas        Asia   42.29592970226644
19                                     Gas  Bangladesh    80.7035976343394
20                                 Nuclear       World   5.023402646739017
21                                 Nuclear        Asia    1.72634685315492
22                                 Nuclear  Bangladesh                 0.0
23                                     Oil       World  15.467663699697468
24                                     Oil        Asia  13.601267873803884
25                                     Oil  Bangladesh    16.3799969497212
26                               Renewable       World    7.11219604259104
27                               Renewable        Asia    1.74383418894015
28                               Renewable  Bangladesh   0.267746691294843
29  Population affected by extreme weather       World                 nan
30  Population affected by extreme weather        Asia                 nan
31  Population affected by extreme weather  Bangladesh                 nan
32                          Internet usage       World   53.42710101990674
33                          Internet usage        Asia   56.57961094120001
34                          Internet usage  Bangladesh               18.02
35                     Pollution Mortality       World                 nan
36                     Pollution Mortality        Asia                 nan
37                     Pollution Mortality  Bangladesh                 nan
38                  Unsafe water mortality       World                 nan
39                  Unsafe water mortality        Asia                 nan
40                  Unsafe water mortality  Bangladesh                 nan
41                            Water access       World   80.91917925398616
42                            Water access        Asia   74.54632165026534
43                            Water access  Bangladesh  55.673246708754505
44                            Water access       Chars    61.4377215849181

In [28]:
summary.to_csv('summary_data.csv')